apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: ${NAMESPACE}-openstack-${CLUSTERNAME}${UNIQUE_SUFFIX}
  namespace: ${NAMESPACE}
spec:
  template: demo-openstack-standalone-cp-0.0.2
  credential: openstack-cluster-identity-cred
  config:
    controlPlaneNumber: 1
    workersNumber: 2
    controlplane:
      flavor: m1.medium
      image:
        filter:
          name: ubuntu-22.04
    worker:
      flavor: m1.medium
      image:
        filter:
          name: ubuntu-22.04
    externalNetwork:
      filter:
        name: public
    authURL: ${OS_AUTH_URL}
    identityRef:
      name: openstack-cloud-config
      cloudName: openstack
      region: RegionOne
