---
apiVersion: v1
kind: Secret
metadata:
  name: openstack-cloud-config
  namespace: k0rdent
type: Opaque
stringData:
  clouds.yaml: |
    clouds:
      openstack:
        auth:
          auth_url: ${OS_AUTH_URL}
          application_credential_id: ${OS_APPLICATION_CREDENTIAL_ID}
          application_credential_secret: ${OS_APPLICATION_CREDENTIAL_SECRET}
        region_name: RegionOne
        interface: public
        identity_api_version: 3
        auth_type: v3applicationcredential
---
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: Credential
metadata:
  name: openstack-cluster-identity-cred
  namespace: ${TESTING_NAMESPACE}
spec:
  description: OpenStack credentials
  identityRef:
    apiVersion: v1
    kind: Secret
    name: openstack-cloud-config
    namespace: ${TESTING_NAMESPACE}
